defaults: &defaults

development:
  <<: *defaults
  twitter:
    consumer_key: j9gCxLRyM9Htqlh2FyYRKZpPz
    consumer_secret: Ah7YbexUtBK0uvFax1mF99CVmxUbgn97mp3kX6R040TlYF9LNP

  github:
    consumer_key: 32a72215a528db8903df
    consumer_secret: 249aaca65a086ed6f9c881899c3dad308927975b

test:
  <<: *defaults

production:
  <<: *defaults
  twitter:
    consumer_key: LJYLR9HWUWBdsgGo8Ud1s8RNI
    consumer_secret: v5qzRNyiiQaFeujvbF19FA9hSFpS0Gi20vzIcbkYHPggVAng2x

  github:
    consumer_key: 696eb0a3cd04183894d3
    consumer_secret: 7016b1ede814268caec6010242e0dde33f95a644